lr9/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace lr9.Controllers
{
    public class HomeController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            var products = new List<Product>()
            {
                new() { Id = 1, Name = "Product1", Price = 10.99m },
                new() { Id = 2, Name = "Product2", Price = 20.49m },
                new() { Id = 3, Name = "Product3", Price = 15.79m },
                new() { Id = 4, Name = "Product4", Price = 5.99m },
                new() { Id = 5, Name = "Product5", Price = 8.50m },
                new() { Id = 6, Name = "Product6", Price = 12.25m }
            };

            ViewBag.City = "Paris";

            return View(products);
        }
    }
}

lr9/ViewComponents/ProductViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace lr9.ViewComponents
{
    public class ProductViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

lr9/ViewComponents/WeatherViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace namespace lr9.ViewComponents
.ViewComponents
{
    public class WeatherViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string city)
        {
            var apiKey = "0d99ca06941bfa04d9b9fb925fa818d9";
            var apiUrl = $"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={apiKey}";
            WeatherResponse? response;
            using (var client = new HttpClient())
            {
                response = await client.GetFromJsonAsync<WeatherResponse>(apiUrl);
            }
            return View(response);
        }
    }

    public class WeatherResponse
    {
        public MainInfo Main { get; set; }
        public WeatherInfo[] Weather { get; set; }
    }

    public class MainInfo
    {
        public float Temp { get; set; }
    }

    public class WeatherInfo
    {
        public string Description { get; set; }
    }
}

lr9/Views/Home/Index.cshtml
@model List<lr9.Product>

@await Component.InvokeAsync("Product")

@await Component.InvokeAsync("Weather", ViewBag.City)

lr9/Views/Shared/Components/Product/Default.cshtml
@model List<lr9.Product>

<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var product in Model)
    {
        <tr>
            <td>@product.Id</td>
            <td>@product.Name</td>
            <td>@product.Price</td>
        </tr>
    }
    </tbody>
</table>

lr9/Views/Shared/Components/Weather/Default.cshtml
@model lr9.ViewComponents.WeatherResponse
<h2>Weather Information</h2>

@if (Model != null)
{
    <p>City: @ViewBag.City</p>
    <p>Temperature: @Model.Main.Temp K</p>
    <p>Weather Description: @Model.Weather[0]?.Description</p>
}
else
{
    <p>No weather information available.</p>
}